### PR TITLE
fixed issue 21 glitch in sierra where title bar would not render correctly

### PR DESCRIPTION
**Pull request by bpenda**
one liner

### CODE REVIEW

**Comment by ymar** [comment]
Great, thanks a lot! Would it be possible to compile a new DMG in Xcode? Since I don't (and I guess also other people) don't have Xcode installed.

**Comment by bpenda** [comment]
I'm on mobile right now so here's a zip instead: 
[PocketCast.app.zip](https://github.com/mortenjust/PocketCastsOSX/files/577017/PocketCast.app.zip)

**Comment by bpenda** [comment]
I updated the titlebar color and added the behavior where closing the window doesn't quit the app too
https://github.com/bpenda/PocketCastsOSX/releases/tag/1.27

**Comment by mortenjust** [comment]
Looks great, thanks!

**Comment by sanderploegsma** [comment]
Hmm @mortenjust, merging this PR also updated your README to his, so now your releases link is off... Just FYI

**Pull request merged**
